### ISSUE TITLE
SIGILL Immediately

### ISSUE THREAD

**Issue by milksteakjellybeans** [go-skynet/llama-cli#5]
Hi, I'm trying this out but I don't get anywhere,  I'm just trying the normal instructions but it dies right away.

```
# docker run -ti --rm quay.io/go-skynet/llama-cli:v0.3  --instruction "What's an alpaca?" --topk 10000
Unable to find image 'quay.io/go-skynet/llama-cli:v0.3' locally
v0.3: Pulling from go-skynet/llama-cli
3e440a704568: Already exists 
68a71c865a2c: Already exists 
670730c27c2e: Already exists 
5a7a2c95f0f8: Already exists 
db119aaf144b: Pull complete 
6f87262882f9: Pull complete 
28b555baed36: Pull complete 
8116bacd01c4: Pull complete 
4e04bf3ce7a2: Pull complete 
cc7bc433a9c3: Pull complete 
226e900d2e08: Pull complete 
3073586a35a4: Pull complete 
fa6b8559eb8a: Pull complete 
dc1c10a22389: Pull complete 
Digest: sha256:a93f23f48cf9df2f1386f6aebf6c1a16cca7c6581e758d4859594e80a6986ee2
Status: Downloaded newer image for quay.io/go-skynet/llama-cli:v0.3
SIGILL: illegal instruction
PC=0x8beac9 m=0 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xc5 0xf0 0x57 0xc9 0x48 0x8b 0x4 0xf8 0x48 0x85 0xc0 0x78 0x1a 0xc4 0xe1 0xf2

goroutine 1 [syscall]:
runtime.cgocall(0x8a33d0, 0xc00018f880)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00018f858 sp=0xc00018f820 pc=0x414f1c
github.com/go-skynet/llama/go._Cfunc_llama_bootstrap(0x225d740, 0x225d5f0, 0x200, 0x0, 0x1)
	_cgo_gotypes.go:124 +0x4c fp=0xc00018f880 sp=0xc00018f858 pc=0x511d4c
github.com/go-skynet/llama/go.New.func1(0xc00002a03b?, 0xa?, {0x9a9bc6?, 0x5?, 0x0?})
	/go/pkg/mod/github.com/go-skynet/llama@v0.0.0-20230321172246-7be5326e18cc/go/llama.go:20 +0x78 fp=0xc00018f8d0 sp=0xc00018f880 pc=0x512258
github.com/go-skynet/llama/go.New({0xc00002a03b, 0xa}, {0xc0001c4b90, 0x2, 0x92eca0?})
	/go/pkg/mod/github.com/go-skynet/llama@v0.0.0-20230321172246-7be5326e18cc/go/llama.go:20 +0xe5 fp=0xc00018f928 sp=0xc00018f8d0 pc=0x512125
main.llamaFromOptions(0x9ce762?)
	/build/main.go:40 +0x109 fp=0xc00018f9a8 sp=0xc00018f928 pc=0x8a15e9
main.main.func3(0xc0001b8420?)
	/build/main.go:239 +0x452 fp=0xc00018fba8 sp=0xc00018f9a8 pc=0x8a2b12
github.com/urfave/cli/v2.(*Command).Run(0xc0001b8420, 0xc0000dac00, {0xc0000ac000, 0x5, 0x5})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:273 +0x9eb fp=0xc00018fe48 sp=0xc00018fba8 pc=0x88e1ab
github.com/urfave/cli/v2.(*App).RunContext(0xc0001645a0, {0xa71a98?, 0xc0000ae000}, {0xc0000ac000, 0x5, 0x5})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616 fp=0xc00018feb8 sp=0xc00018fe48 pc=0x88b016
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:309
main.main()
	/build/main.go:262 +0x931 fp=0xc00018ff80 sp=0xc00018feb8 pc=0x8a2191
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc00018ffe0 sp=0xc00018ff80 pc=0x4484e7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00018ffe8 sp=0xc00018ffe0 pc=0x477d61

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000042fb0 sp=0xc000042f90 pc=0x448916
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000042fe0 sp=0xc000042fb0 pc=0x448750
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000042fe8 sp=0xc000042fe0 pc=0x477d61
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000043780 sp=0xc000043760 pc=0x448916
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000437c8 sp=0xc000043780 pc=0x434bee
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000437e0 sp=0xc0000437c8 pc=0x429ec6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000437e8 sp=0xc0000437e0 pc=0x477d61
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00006a000?, 0xa6a010?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000043f70 sp=0xc000043f50 pc=0x448916
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xe03d60)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000043fa0 sp=0xc000043f70 pc=0x432b33
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000043fc8 sp=0xc000043fa0 pc=0x433105
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000043fe0 sp=0xc000043fc8 pc=0x429e66
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x477d61
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0xe04c80?, 0xe0?, 0x24?, 0xc000042770?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000042628 sp=0xc000042608 pc=0x448916
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000427e0 sp=0xc000042628 pc=0x428f07
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x477d61
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x45

rax    0xa9ca80
rbx    0x225d680
rcx    0x224b010
rdx    0x1
rdi    0x0
rsi    0x1
rbp    0x7ffc8d90e620
rsp    0x7ffc8d90e058
r8     0x2
r9     0x1
r10    0xffffffffffffff65
r11    0x7f4b70e8e720
r12    0x20
r13    0x200
r14    0x7cff
r15    0x1000
rip    0x8beac9
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0
```

**Comment by milksteakjellybeans** [comment]
I believen this is a problem with my cpu lacking avx instruction support

**Comment by mudler** [comment]
right, looks like the instruction set is not present, you can try building locally https://github.com/go-skynet/llama-cli#build-locally, but I'm afraid it won't work or either be really slow.
